### ISSUE TITLE
Unable to move property using modify

### ISSUE THREAD

**Issue by VasudevanGIT** [akamai/cli-property#30]
$ ./akamaiProperty modify dummywwwtest --move 101490
Modifying property dummywwwtest
Moving dummywwwtest to 0
ERROR:  {}
TypeError: destGroup.match is not a function
    at WebSite._moveProperty (/Users/m939241/Desktop/Akamai/cli-property/src/website.js:1268:23)
    at WebSite.moveProperty (/Users/m939241/Desktop/Akamai/cli-property/src/website.js:1987:21)
    at Promise.then.then.then.then.then.then (/Users/m939241/Desktop/Akamai/cli-property/bin/akamaiProperty:256:29)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3

**Comment by plermant** [comment]
try
--move grp_101490

**Comment by VasudevanGIT** [comment]
A4774220:bin m939241$ ./akamaiProperty modify dummywww1 --move grp_102382
Modifying property dummywww1
Moving dummywww1 to 0
ERROR:  {}
TypeError: destGroup.match is not a function
    at WebSite._moveProperty (/Users/m939241/Desktop/Akamai/cli-property/src/website.js:1268:23)
    at WebSite.moveProperty (/Users/m939241/Desktop/Akamai/cli-property/src/website.js:1987:21)
    at Promise.then.then.then.then.then.then (/Users/m939241/Desktop/Akamai/cli-property/bin/akamaiProperty:256:29)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3

**Comment by plermant** [comment]
can you also add the contract number as an input param - see issue #31

**Comment by synedra** [comment]
Do you have User Admin turned on in your permissions?  I'll look into this in any case, but that might be the issue.

**Comment by VasudevanGIT** [comment]
Thanks for your input Pierre, tried that... modify doesn't seem to have contract param..
A4774220:bin m939241$ ./akamaiProperty modify pierre23 --move grp_102382 --contract ctr_1-1U72M7

  error: unknown option `--contract'

**Comment by VasudevanGIT** [comment]
Kirsten - I am not sure about admin permission, how can i tell if its enabled ..

**Comment by synedra** [comment]
You can't do it with just papi permissions.  You need permission for the user admin API as well.

K

**Comment by VasudevanGIT** [comment]
Tested with an API User that has access to READ-WRITE on User Admin as well as PAPI and still got same exception


./akamaiProperty modify july18assets --move grp_102382 --section adminc4d
Modifying property july18assets
Moving july18assets to 0
ERROR:  {}
TypeError: destGroup.match is not a function
    at WebSite._moveProperty (/Users/m939241/Desktop/Akamai/cli-property/src/website.js:1268:23)
    at WebSite.moveProperty (/Users/m939241/Desktop/Akamai/cli-property/src/website.js:1987:21)
    at Promise.then.then.then.then.then.then (/Users/m939241/Desktop/Akamai/cli-property/bin/akamaiProperty:256:29)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3

**Comment by synedra** [comment]
Ok, I'll take a look.  I may need access to credentials to recreate the problem.

Does the user have PAPI access at the account level? And User Admin at the account level?

This may be required for move to work.

Thanks,
Kirsten

**Comment by synedra** [comment]
This is fixed now, sorry for the trouble!

**Comment by VasudevanGIT** [comment]
Hi Kristen,

Thanks for looking into this..

Doesn't seem to be fixed.. still facing same error..

Modifying property mcom-int034auth
Moving mcom-int034auth to 0
ERROR:  {}
TypeError: destGroup.match is not a function
    at WebSite._moveProperty (/Users/m939241/Desktop/Akamai/cli-property/src/website.js:1268:23)
    at WebSite.moveProperty (/Users/m939241/Desktop/Akamai/cli-property/src/website.js:1987:21)
    at Promise.then.then.then.then.then.then (/Users/m939241/Desktop/Akamai/cli-property/bin/akamaiProperty:256:29)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3

**Comment by synedra** [comment]
How did you update your version of akamai property?  It's working for me on my system.

Kirsten

**Comment by VasudevanGIT** [comment]
My bad.. didnt clone latest cli.. 

Now seeing a different error.. might have something to do with access.. ?

A4774220:bin m939241$ ./akamaiProperty modify mcom-int034auth --move grp_102382 --section adminc4d
Modifying property mcom-int034auth
Moving mcom-int034auth to grp_102382
... retrieved rules formats: 1754.043ms
... searching propertyName for mcom-int034auth
... searching hostname for mcom-int034auth
... searching edgeHostname for mcom-int034auth
Cannot locate property using search
Initializing property cache
Init PropertyManager cache (hostnames and property list)
... retrieving list of Group Ids
... retrieving properties from 17 groups
... no permissions, ignoring  {ctr_1-1U72M7 : grp_54598}
... no permissions, ignoring  {ctr_3-1AZ95HC : grp_54598}
... retrieving Hosts from 122 properties
Init PropertyManager cache: 2118.895ms
... no permissions, ignoring  {ctr_1-1U72M7 : grp_54598}
... no permissions, ignoring  {ctr_3-1AZ95HC : grp_54598}
Gathering asset ID for property
... requesting: 322.304ms
ERROR:  "{\"localizedMessage\":\"You are not authorized to perform this operation.\",\"detail\":\"Not Authorized to view this resource.\",\"title\":\"Forbidden\",\"httpStatus\":403,\"appError\":\"You are not authorized to perform this operation.\"}"
